### ISSUE TITLE
[Feature Request] Define custom redirects

### ISSUE THREAD

**Issue by grgur** [ModusCreateOrg/capsule#29]
It would be nice to set up custom redirect rules. We found that useful in Modus Labs [(see here)](https://github.com/ModusCreateOrg/labs/blob/master/static/_redirects) based on [Netlify config](https://www.netlify.com/docs/redirects/)

**Comment by rpigu-i** [comment]
This has been added in. A separate ticket is recording the work for versioning around this.

**Comment by grgur** [comment]
Thank you team :)
