### ISSUE TITLE
Pre-init configuration

### ISSUE THREAD

**Issue by grgur** [ModusCreateOrg/capsule#49]
`init` looks like the command we start with. Here's what I expect from it:
* Create a configuration file
* Create any metadata files such as cloudformation templates
* DO NOT deploy

Then I would expect `capsule deploy` that does the work.

Does this make sense?

**Comment by rpigu-i** [comment]
Yep, we can change it up to do that.

**Comment by rpigu-i** [comment]
We now have a capsule.json file which is created by the `init` command, and used by the `deploy` command.

**Comment by rpigu-i** [comment]
Done!
