### ISSUE TITLE
Project name as argument

### ISSUE THREAD

**Issue by grgur** [ModusCreateOrg/capsule#51]
Without reading the docs I thought I was expected to use `capsule init my-project-name`

What does the team think of that approach?

**Comment by rpigu-i** [comment]
We have the `init` command, however there are still some parameters you would need to pass in (subdomain/domain). What we could do is modify the command line (capsule.js), so that if you don't pass in any parameters it defaults to using the configuration JSON file?

**Comment by grgur** [comment]
works!

**Comment by rpigu-i** [comment]
All done!
