### ISSUE TITLE
MVP1 - Update README and create a docs section

### ISSUE THREAD

**Issue by facundovictor** [ModusCreateOrg/capsule#65]
We should:
1. Create a docs folder to contain specific documentation, with categories like:
  - General capsule cli explanation
  - Cloudformation templates explanation including the architecture graph
  - AWS credentials setup, suggestions and links to useful AWS docs.
  - Explanation for capsule config
  - Contribution section:
     - how to create issues
     - how to creat prs
     - how to setup the dev env
     - how to test changes
     - how to release next version
     - "thanks to"
     - others?
  - FAQs
2. Update README to be the main project presentation and reference docs in under docs/ folder.
3. Add badges for:
  - codebuild test passing, 
  - npm version
  - download count
  - license fossa scan

**Comment by rpigu-i** [comment]
Badges have been added along with the other items listed in here.

Going to close this out
